sudo: false
dist: xenial
language: python
python: "3.7"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pipenv
install:
  - pip install --upgrade pip pipenv
  - pipenv clean && pipenv --rm
  - pipenv install --dev --deploy
script:
  - make clean fmt lint build
notifications:
  email: false
